name: GitHub Profile 3D Contribution

on:
  schedule:
    - cron: "0 18 * * *"  # runs daily at 03:00 JST (18:00 UTC)
  workflow_dispatch:

jobs:
  build:
    name: Generate GitHub Profile 3D Contribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate 3D Contribution
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "generated"
          git push
