name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight
  workflow_dispatch:      # manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Kanakbaghel
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg
            ./output/ocean.gif

      - name: Commit snake files
        uses: EndBug/add-and-commit@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Auto-update snake & 3D animation"
          add: "output"
