name: Update Badge Data

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch repo count
        run: |
          curl -s https://api.github.com/users/Kanakbaghel | jq '.public_repos' > repo_count.txt

      - name: Commit updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add repo_count.txt
          git commit -m "Auto-update repo count"
          git push
